=== Tuananhkt111/Workplace/Java Learning/XML/PROJECT_DATDVTSE62865 _Client/PROJECT_DATDVTSE62865 _Client/web/WEB-INF/categories.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/categories"
            xmlns="http://xml.netbeans.org/schema/categories"
            elementFormDefault="qualified"
>
    <xsd:element name="categories">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="category" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="link" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Tuananhkt111/Workplace/Java Learning/XML/PROJECT_DATDVTSE62865 _Client/PROJECT_DATDVTSE62865 _Client/build/web/WEB-INF/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:categories
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.org/schema/categories'
    xsi:schemaLocation='http://xml.netbeans.org/schema/categories categories.xsd'>
    <category>
        <name>gffs</name>
        <link>sefesfesf</link>
    </category>
    <category>
        <name>fesfesf</name>
        <link>esffesf</link>
    </category>
    <category>
        <name>esfsef</name>
        <link>fesfes</link>
    </category>
</ns1:categories>
