=== Tuananhkt111/Workplace/Java Learning/XML/PROJECT_DATDVTSE62865 _Client/PROJECT_DATDVTSE62865 _Client/build/web/WEB-INF/websiteCategory.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/websiteCategory"
            xmlns="http://xml.netbeans.org/schema/websiteCategory"
            elementFormDefault="qualified">

    <xsd:element name="websiteCategory">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="category" type="CategoryDTO"/>
                <xsd:element name="id" type="xsd:int"/>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="url" type="xsd:string"/>
                <xsd:element name="website" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="CategoryDTO">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:int"/> 
            <xsd:element name="levelAuth" type="xsd:int"/> 
            <xsd:element name="name" type="xsd:string"/> 
            </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Tuananhkt111/Workplace/Java Learning/XML/PROJECT_DATDVTSE62865 _Client/PROJECT_DATDVTSE62865 _Client/web/WEB-INF/newXMLDocument1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:websiteCategory
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.org/schema/websiteCategory'
    xsi:schemaLocation='http://xml.netbeans.org/schema/websiteCategory websiteCategory.xsd'>
    <ns1:id></ns1:id>
    <ns1:name></ns1:name>
    <ns1:url></ns1:url>
    <ns1:website></ns1:website>
    <ns1:category>
        <ns1:id></ns1:id>
        <ns1:name></ns1:name>
        <ns1:levelAuth></ns1:levelAuth>
    </ns1:category>

</ns1:websiteCategory>
